name: hello-world-deployment

releases:
- name: hello-world
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: server
  azs: [z1]
  instances: 1
  vm_type: n1-standard-1
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: hello-world
    templates:
    - name: hello-world
      release: hello-world
